## Auto-generated by the Fivetran Ingestion Portal — do not hand-edit.
## Source system: test3
## Environment:    dev
## Generated:      2026-07-22T05:53:57.422Z

module "test3_connector" {
  source = "git::https://github.com/chandu5012/vdp-fivetran-terraform-module.git?ref=v1"

  connector_id           = "short_retrieve"
  schema_change_handling = "ALLOW_COLUMNS"
  sync_frequency_minutes = 60

  tables = [
    {
      source_schema = "public"
      source_table  = "inventory"
      target_table  = "inventory_1"
    },
  ]
}
